name: Code tests
run-name: Integration and unit tests 🩺
on: [push, pull_request]
concurrency:
  group: ${{ github.ref }}-it
  cancel-in-progress: true
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 🛎️
        uses: actions/checkout@v4
      -
        name: Setup Python 3.12 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      -
        name: Install flit
        run: pip install flit
      -
        name: Install dependencies
        run: make install-dev
      -
        name: Run integration tests 🩺
        run: |
          python \
            -m \
              pytest \
                tests/
